### ISSUE TITLE
Code snippet not rendering right in discussion question

### ISSUE THREAD

**Issue by abby-anderson** [learn-co-curriculum/mod-1-discussion-questions-ruby-fundamentals-review#4]
### Canvas Link

https://learning.flatironschool.com/courses/4378/discussion_topics/12149?module_item_id=310815

### Concern

Hi there! If you follow the link to this discussion question page in Canvas, you can see that the code snippets in questions 11 and 12 didn't render correctly! It looks like they might have some issues with the three backticks (''').

**Comment by ihollander** [comment]
Thanks for letting us know about this issue @abby-anderson - the Readme formatting has been [fixed](https://github.com/learn-co-curriculum/mod-1-discussion-questions-ruby-fundamentals-review/commit/524e5bf009cea0e1bf489713afd02d0764b39e88) and the content has also been updated in Canvas.
